### YamlMime:BusinessCentralApplicationObject
fqName: FreddyK.BingMaps.Setup."BingMaps Settings"
alId: ID 74125
namespace: FreddyK.BingMaps.Setup
baseKind: Page
kind: Page
parent: N:Module::BingMaps.PTE::Namespace::FreddyK.BingMaps.Setup
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: PageType
  value: API
  promoted: true
- name: Caption
  value: BingMaps Settings
  promoted: false
- name: APIPublisher
  value: microsoft
  promoted: false
- name: APIGroup
  value: bingmaps
  promoted: false
- name: APIVersion
  value: "'v1.0'"
  promoted: false
- name: EntityName
  value: settings
  promoted: false
- name: EntitySetName
  value: settings
  promoted: false
- name: SourceTable
  value: "823"
  promoted: true
  xrefType:
    name: Microsoft.Utilities."Name/Value Buffer"
    isExternal: true
- name: DelayedInsert
  value: "True"
  promoted: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
commentId: O:Page::FreddyK#BingMaps#Setup#BingMaps Settings
uid: O:Page::FreddyK#BingMaps#Setup#BingMaps_Settings
name: '"BingMaps Settings"'
